name: Update Mastodon posts data

on:
  schedule:
    - cron: '55 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-posts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install sqlite-utils
        run: pipx install sqlite-utils
        env:
          PIPX_DEFAULT_PYTHON: python
      - name: Install mastodon-to-sqlite
        run: pipx install mastodon-to-sqlite
        env:
          PIPX_DEFAULT_PYTHON: python
      - name: Update Mastodon posts DB
        run: fish export-posts-to-content.fish
        working-directory: mastodon/
      - name: Export Mastodon posts
        run: bash update-statuses.bash
        working-directory: mastodon/
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.repository.default_branch }}
